<?php:

$title = 'Entries';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('entry', array('action'=>'add'));?>">Add new entry</a>
</p>

<table class="table">
<tr>
    <th>Title</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($entryes as $entry) : ?>
<tr>
    <td><?php echo $this->escapeHtml($entry->url);?></td>
    <td>
        <a href="<?php echo $this->url('entry',
            array('action'=>'edit', 'id' => $entry->id));?>">Edit</a>
        <a href="<?php echo $this->url('entry',
            array('action'=>'delete', 'id' => $entry->id));?>">Delete</a>
    </td>
</tr>
<?php endforeach; ?>
</table>