<?php:

$title = 'Entries';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('entry', array('action'=>'add'));?>">Add new entry</a>
</p>

<table class="table">
<tr>
    <th>Description</th>
    <th>Title</th>
     <th>Type</th>
    <th>Actions</th>
</tr>
<?php foreach ($entries as $entry) : ?>
<?php //print_r($entry);die;?>
<tr>
<td><?php echo $this->escapeHtml($entry->getDescription());?></td>
    <td><?php echo $this->escapeHtml($entry->getUrl());?></td>
    <td><?php echo $this->escapeHtml($entry->getEntrytype()->getEntryTypeString());?></td>
    <td>
        <a href="<?php echo $this->url('entry',
            array('action'=>'edit', 'id' => $entry->getId()));?>">Edit</a>
        <a href="<?php echo $this->url('entry',
            array('action'=>'delete', 'id' => $entry->getId()));?>">Delete</a>
    </td>
</tr>
<?php endforeach; ?>
</table>